#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

APP_NAME="Router Menu"
EXECUTABLE="Router Menu"
DIST="dist"
APP="$DIST/$APP_NAME.app"
DERIVED="$DIST/DerivedData"
PROJECT="$APP_NAME.xcodeproj"

# xcodebuild, not `swift build` + a hand-assembled bundle: the widget is an
# app extension, and only xcodebuild can build a nested .appex, embed it in
# Contents/PlugIns and sign the whole tree inside-out. Package.swift still
# owns the dependencies and still runs the test suite.
if ! command -v xcodegen >/dev/null 2>&1; then
  echo "xcodegen not found. Install it with: brew install xcodegen" >&2
  exit 1
fi

echo "==> Generating $PROJECT"
xcodegen generate

echo "==> App icon"
./scripts/make-icon.sh

# SIGN_IDENTITY enables Developer ID signing (release); ad-hoc by default.
SIGN_IDENTITY="${SIGN_IDENTITY:--}"

XCB=(xcodebuild
  -project "$PROJECT"
  -scheme "$APP_NAME"
  -configuration Release
  -derivedDataPath "$DERIVED"
  # Universal, matching the old `swift build --arch arm64 --arch x86_64`.
  ARCHS="arm64 x86_64"
  ONLY_ACTIVE_ARCH=NO)

# Always built unsigned, then signed by hand below — for BOTH paths.
# Letting xcodebuild sign requires a provisioning profile the moment an
# entitlement needs one (the App Group does), and it hard-fails without it:
#   "RouterMenuWidget" requires a provisioning profile.
# Signing afterwards is what the pre-xcodegen pipeline did, and it keeps a
# Developer ID release building on a machine that has no profile installed.
echo "==> Building (unsigned; signed below)"
"${XCB[@]}" CODE_SIGNING_ALLOWED=NO build

BUILT="$DERIVED/Build/Products/Release/$APP_NAME.app"
if [[ ! -d "$BUILT" ]]; then
  echo "Build produced no app at $BUILT" >&2
  exit 1
fi

echo "==> Staging $APP"
rm -rf "$APP"
mkdir -p "$DIST"
# ditto, not cp: preserves the signatures and symlinks already in the bundle.
ditto "$BUILT" "$APP"

# The whole point of the migration — if the extension is missing, the widget
# silently never appears, and nothing later in the pipeline would notice.
APPEX="$APP/Contents/PlugIns/RouterMenuWidget.appex"
if [[ ! -d "$APPEX" ]]; then
  echo "Widget extension missing from the bundle: $APPEX" >&2
  exit 1
fi
if ! /usr/libexec/PlistBuddy -c 'Print :NSExtension:NSExtensionPointIdentifier' \
     "$APPEX/Contents/Info.plist" 2>/dev/null | grep -q widgetkit; then
  echo "Widget extension has no widgetkit extension point — macOS would ignore it." >&2
  exit 1
fi

# Both entitlement files are GENERATED by xcodegen from project.yml. An empty
# `properties:` map silently rewrites them to an empty dict, which builds and
# signs cleanly and produces a widget that can never read the shared container.
for PAIR in "Resources/entitlements.plist:app" \
            "Resources/widget-entitlements.plist:widget"; do
  FILE="${PAIR%%:*}"
  WHICH="${PAIR##*:}"
  if ! /usr/libexec/PlistBuddy -c 'Print :com.apple.security.application-groups:0' \
       "$FILE" 2>/dev/null | grep -q "group.io.8lines.router-menu"; then
    echo "The $WHICH entitlements ($FILE) carry no App Group." >&2
    echo "The widget cannot read the app's data without it. Check project.yml." >&2
    exit 1
  fi
done

# Inside-out, never --deep: --deep re-signs nested code with the OUTER
# bundle's arguments, which strips the extension's own entitlements and
# leaves a widget macOS refuses to load.
FW="$APP/Contents/Frameworks/Sparkle.framework"

if [[ "$SIGN_IDENTITY" == "-" ]]; then
  echo "==> Ad-hoc signing"
  SIGN=(codesign --force --sign -)
else
  echo "==> Developer ID signature: $SIGN_IDENTITY"
  SIGN=(codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY")
fi

# Nested code first, parent last — notarization rejects the other order.
"${SIGN[@]}" "$FW/Versions/B/XPCServices/Downloader.xpc"
"${SIGN[@]}" "$FW/Versions/B/XPCServices/Installer.xpc"
"${SIGN[@]}" "$FW/Versions/B/Updater.app"
"${SIGN[@]}" "$FW/Versions/B/Autoupdate"
"${SIGN[@]}" "$FW/Versions/B"
"${SIGN[@]}" "$FW"
"${SIGN[@]}" "$APP/Contents/Frameworks/RouterMenu.framework"
"${SIGN[@]}" --entitlements "Resources/widget-entitlements.plist" "$APPEX"
"${SIGN[@]}" --entitlements "Resources/entitlements.plist" "$APP"

codesign --verify --deep --strict --verbose=2 "$APP"
codesign --verify --strict --verbose=2 "$APPEX"

echo "==> Launch smoke test"
# Nothing else in this pipeline ever runs the assembled app, so a bundle that
# fatal-errors at startup (e.g. a missing SwiftPM resource bundle) used to ship
# silently: the app is LSUIElement, so a dead process looks like "no icon yet".
SMOKE_LOG="$(mktemp -t router-menu-smoke)"
set +e
"$APP/Contents/MacOS/$EXECUTABLE" >"$SMOKE_LOG" 2>&1 &
SMOKE_PID=$!
sleep 3
kill -0 "$SMOKE_PID" 2>/dev/null
SMOKE_ALIVE=$?
set -e

if [[ "$SMOKE_ALIVE" -ne 0 ]]; then
  wait "$SMOKE_PID" 2>/dev/null || true
  {
    echo "Launch smoke test FAILED: $EXECUTABLE exited within 3 seconds."
    echo "The assembled app crashes on launch and must not be shipped."
    echo "--- output ---"
    cat "$SMOKE_LOG"
    echo "--------------"
    # stderr is often empty here: dispatch assertions, Swift runtime traps
    # and ObjC exceptions land in the crash report and unified log instead.
    CRASH=""
    for _ in 1 2 3 4 5 6; do
      sleep 5
      CRASH="$(ls -t "$HOME/Library/Logs/DiagnosticReports/"*.ips \
                     /Library/Logs/DiagnosticReports/*.ips 2>/dev/null | head -1 || true)"
      [[ -n "$CRASH" ]] && break
    done
    if [[ -n "$CRASH" ]]; then
      echo "--- crash report: $CRASH ---"
      cat "$CRASH" || true
    else
      echo "(no crash report appeared within 30s)"
    fi
    echo "--- unified log (last 3m, $EXECUTABLE) ---"
    log show --last 3m --style compact \
      --predicate "process == \"$EXECUTABLE\"" 2>/dev/null | tail -60 || true
    # Hardened runtime forbids attaching, so debug an ad-hoc re-signed copy.
    # If that copy survives instead, the crash is signing-related — also news.
    echo "--- lldb backtrace (ad-hoc re-signed copy) ---"
    LLDB_APP="$DIST/smoke-debug.app"
    rm -rf "$LLDB_APP"
    cp -R "$APP" "$LLDB_APP"
    codesign --force --deep --sign - "$LLDB_APP" 2>/dev/null || true
    ( sleep 30; pkill -f smoke-debug ) &
    KILLER=$!
    lldb --batch -o run -k 'thread backtrace all' -k quit \
      "$LLDB_APP/Contents/MacOS/$EXECUTABLE" 2>&1 | tail -60 || true
    kill "$KILLER" 2>/dev/null || true
    rm -rf "$LLDB_APP"
  } >&2
  rm -f "$SMOKE_LOG"
  exit 1
fi

kill "$SMOKE_PID" 2>/dev/null || true
wait "$SMOKE_PID" 2>/dev/null || true
rm -f "$SMOKE_LOG"
echo "    App survived launch (still running after 3s)"

echo "==> Done: $APP"
